apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: "configmap-{{ .Values.global.namespace }}"
data:
  DATABASE_URL: {{ .Values.global.apiConfig.database.url | quote }}
  LOG_LEVEL: {{ .Values.global.apiConfig.logLevel | quote }}