version: '3.9'

services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    # For see logs from app
    volumes:
      - type: bind
        source: ./docker-data/tester.log
        target: /app/tester.log