{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "device-registration-api.fullname" . }}
  labels:
    {{- include "device-registration-api.labels" . | nindent 4 }}
data:
{{- end }}
