apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.global.namespace }} # name of the namespace
    annotations:
        "helm.sh/hook": "pre-install"
        "helm.sh/hook-order": "1"
        "helm.sh/hook-weight": "0"
    labels:
        name: {{ .Values.global.namespace }}
        azure-key-vault-env-injection: enabled
