{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "statistics-api.fullname" . }}
  labels:
    {{- include "statistics-api.labels" . | nindent 4 }}
data:
  DEVICE_API_URL: {{ .Values.deviceApi.url | quote }}
{{- end }}
