{{- if .Values.enabled -}}
{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ include "statistics-api.fullname" . }}
  labels:
    {{- include "statistics-api.labels" . | nindent 4 }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      {{- include "statistics-api.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
